//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "Torture.h"
#include "Torture_Torture_Infrastructure_CpuStatsProvider.h"

using namespace Torture::Torture;


HRESULT Library_Torture_Torture_Infrastructure_CpuStatsProvider::GetCpuUsageInternal___STATIC__U2__SZARRAY_I1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        CLR_RT_TypedArray_INT8 param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT8_ARRAY( stack, 0, param0 ) );

        uint16_t retValue = CpuStatsProvider::GetCpuUsageInternal( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_UINT16( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
